version: '3.4'

services:
  usermanagement:
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile 
    depends_on: 
        - db
  db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        SA_PASSWORD: "2Secure*Password2"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"